name=GyverLCD
version=1.0.5
author=AlexGyver <alex@alexgyver.ru>
maintainer=AlexGyver <alex@alexgyver.ru>
sentence=Lightweight fast LCD I2C library with software UTF-8 support
paragraph=Lightweight fast LCD I2C library with software UTF-8 support
category=Display
url=https://github.com/GyverLibs/GyverLCD
architectures=*